### ISSUE TITLE
Create cadvisor container failed

### ISSUE THREAD

**Issue by lolfloppydisc** [rishavnandi/ansible_homelab#3]
fatal: [192.168.10.112]: FAILED! => {"changed": false, "msg": "Error starting container d378655d8852069c67295403da8c47a755f07e4b307b6da82839e45e61346f42: 500 Server Error for http+docker://localhost/v1.42/containers/d378655d8852069c67295403da8c47a755f07e4b307b6da82839e45e61346f42/start: Internal Server Error (\"error gathering device information while adding custom device \"/dev/kmsg\": no such file or directory\")"}

**Comment by rishavnandi** [comment]
@lolfloppydisc I think this might be happening as I missed adding "privileged: true" to the cadvisor container as I had updated the image of cadvisor I'm using from a third party developer to the official Google one.. I'll test it out soon..if that doesn't fix it then I'll have to troubleshoot it a bit as it's working fine for me

And another heads up there's a small issue with the bootstrap script..the authelia argon2id password is not written to the vars.yml properly using the script as the special characters cause issues in the bash script so you'll have to update it manually if you are using it..
