### ISSUE TITLE
Error when running ansible-playbook main.yml

### ISSUE THREAD

**Issue by karlnotcarl** [rishavnandi/ansible_homelab#5]
I am new to using Ansible so I may be doing something wrong, but when I run the command "ansible-playbook main.yml", I receive the error:
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 66, in <module>
    from ansible.utils.display import Display, initialize_locale
ImportError: cannot import name 'initialize_locale' from 'ansible.utils.display' (/home/fakename/.local/lib/python3.10/site-packages/ansible/utils/display.py)

**Comment by rishavnandi** [comment]
@karlnotcarl Seems like there might be an issue with your Ansible install, I would recommend uninstalling it and then reinstalling it using pip and then checking if the issue persists... let me know if that helps!

**Comment by karlnotcarl** [comment]
@rishavnandi That seems to have solved it. Thanks for your help.
