### ISSUE TITLE
AWS

### ISSUE THREAD

**Issue by defconxt** [rishavnandi/ansible_homelab#7]
Wasn't sure where else to ask this, but do you actually host all of this in AWS, or was that more of a project to learn terraform? If the former, how much does that run a month? That's gotta be pricey.

Thanks for the great playbooks.

**Comment by rishavnandi** [comment]
Hi!
I actually run all this on a free Oracle VPS that has a 4 core ARM CPU and 24 gigs of RAM.
The Terraform script is just there as I used to deploy and take down instances to make sure the playbooks were working on AWS as well, I also tried the playbooks with Linode servers and that works too but I only tested the dual core servers in both platforms as I didn't want to spend too much testing.
From my experience on dual core servers you cannot run all of the containers included as the deployment slows down a lot and freezes up indicating the server cant handle more containers so you will most likely need to deploy only essentials or pay for a better VPS.
